# Generated by Django 5.0.6 on 2024-07-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Statuse',
        ),
    ]
